[project]
name = "pybash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "toml>=0.10.2",
    "types-toml>=0.10.8.20240310",
]
